"""Data schemas / models for the ROX Test application."""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class Lead:
    """A lead discovered by OpenOutreach."""

    first_name: str
    last_name: str
    company: str = ""
    title: str = ""
    website: str = ""
    linkedin_url: str = ""
    reason: str = ""
    email: str = ""
    lead_id: str = ""

    @property
    def name(self) -> str:
        return f"{self.first_name} {self.last_name}".strip()

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Lead":
        """Build a Lead from an OpenOutreach output row."""
        return cls(
            first_name=data.get("first_name", "") or "",
            last_name=data.get("last_name", "") or "",
            company=data.get("company", "") or "",
            title=data.get("title", "") or "",
            website=data.get("website", "") or "",
            linkedin_url=data.get("linkedin_url", "") or "",
            reason=data.get("reason", "") or "",
            email=data.get("email", "") or "",
            lead_id=str(data.get("lead_id", "")) or "",
        )


@dataclass
class Campaign:
    """A lead generation campaign stored in SQLite."""

    id: Optional[int]
    event_name: str
    market: str
    created_at: Optional[str] = None


@dataclass
class TargetingInstructions:
    """Result of the Groq targeting generation step."""

    instructions: str
    prompt_sent: str


@dataclass
class OpenOutreachResult:
    """Result of running the OpenOutreach CLI."""

    leads: List[Lead]
    command: str
    stdout: str
    stderr: str
    exit_code: int

    @property
    def success(self) -> bool:
        return self.exit_code == 0


@dataclass
class EnrichedProfile:
    """Normalized form of an Apify Actor 2 profile result."""

    name: str = ""
    headline: str = ""
    about: str = ""
    company: str = ""
    role: str = ""
    experience: List[Dict[str, Any]] = field(default_factory=list)
    education: List[Dict[str, Any]] = field(default_factory=list)
    skills: List[str] = field(default_factory=list)
    location: str = ""
    email: str = ""
    raw: Dict[str, Any] = field(default_factory=dict)


@dataclass
class EmailDraft:
    """Personalized email generated by Groq."""

    subject: str = ""
    body: str = ""
    to: str = ""
    prompt_sent: str = ""


@dataclass
class ApifyRunResult:
    """Result of an Apify Actor run."""

    actor_id: str
    items: List[Dict[str, Any]]
    run_id: str = ""
    status: str = ""
    raw_debug: str = ""